In [ ]:
import pandas as pd
df=pd.read_csv('dat_bmw.csv')
df.head()
df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3072 entries, 0 to 3071
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              3072 non-null   int64
 1   Month             3072 non-null   int64
 2   Region            3072 non-null   object
 3   Model             3072 non-null   object
 4   Units_Sold        3072 non-null   int64
 5   Avg_Price_EUR     3072 non-null   int64
 6   Revenue_EUR       3072 non-null   int64
 7   BEV_Share         3072 non-null   float64
 8   Premium_Share     3072 non-null   float64
 9   GDP_Growth        3072 non-null   float64
 10  Fuel_Price_Index  3072 non-null   float64
dtypes: float64(4), int64(5), object(2)
memory usage: 264.1+ KB

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3072 entries, 0 to 3071
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              3072 non-null   int64
 1   Month             3072 non-null   int64
 2   Region            3072 non-null   object
 3   Model             3072 non-null   object
 4   Units_Sold        3072 non-null   int64
 5   Avg_Price_EUR     3072 non-null   int64
 6   Revenue_EUR       3072 non-null   int64
 7   BEV_Share         3072 non-null   float64
 8   Premium_Share     3072 non-null   float64
 9   GDP_Growth        3072 non-null   float64
 10  Fuel_Price_Index  3072 non-null   float64
dtypes: float64(4), int64(5), object(2)
memory usage: 264.1+ KB

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [4]:
df.isnull()

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
3067,False,False,False,False,False,False,False,False,False,False,False
3068,False,False,False,False,False,False,False,False,False,False,False
3069,False,False,False,False,False,False,False,False,False,False,False
3070,False,False,False,False,False,False,False,False,False,False,False
3071,False,False,False,False,False,False,False,False,False,False,False

In [5]:
df.isnull().sum()

Year                0
Month               0
Region              0
Model               0
Units_Sold          0
Avg_Price_EUR       0
Revenue_EUR         0
BEV_Share           0
Premium_Share       0
GDP_Growth          0
Fuel_Price_Index    0
dtype: int64

In [7]:
df_fill=df.fillna(0)
df_fill

,Year,Month,Region,Model,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
0,2018,1,Europe,3 Series,7822,47482,371404204,0.011,19.12,3.50,1.00
1,2018,1,Europe,5 Series,10280,61685,634121800,0.019,19.12,3.50,1.00
2,2018,1,Europe,X3,3105,58433,181434465,0.022,19.12,3.50,1.00
3,2018,1,Europe,X5,7420,67955,504226100,0.021,19.12,3.50,1.00
4,2018,1,Europe,X7,8474,92300,782150200,0.035,19.12,3.50,1.00
...,...,...,...,...,...,...,...,...,...,...,...
3067,2025,12,RestOfWorld,X5,9281,68198,632945638,0.201,5.89,2.37,1.41
3068,2025,12,RestOfWorld,X7,12785,91839,1174161615,0.203,5.89,2.37,1.41
3069,2025,12,RestOfWorld,i4,4906,63437,311221922,0.180,5.89,2.37,1.41
3070,2025,12,RestOfWorld,iX,7871,73867,581407157,0.196,5.89,2.37,1.41
3071,2025,12,RestOfWorld,MINI,6732,41811,281471652,0.167,5.89,2.37,1.41

In [8]:
df.dtypes

Year                  int64
Month                 int64
Region               object
Model                object
Units_Sold            int64
Avg_Price_EUR         int64
Revenue_EUR           int64
BEV_Share           float64
Premium_Share       float64
GDP_Growth          float64
Fuel_Price_Index    float64
dtype: object

In [5]:
import pandas as pd
data={"State":["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia"],
"Population":[4903185,731545,7278717,3017804,39538223,5758736,3565287,973764,21477737,10617423],
"Area":[52420,665384,113990,53179,163695,104094,5543,2489,65758,59425]}
df=pd.DataFrame(data)

In [6]:
df

         State  Population    Area
0      Alabama     4903185   52420
1       Alaska      731545  665384
2      Arizona     7278717  113990
3     Arkansas     3017804   53179
4   California    39538223  163695
5     Colorado     5758736  104094
6  Connecticut     3565287    5543
7     Delaware      973764    2489
8      Florida    21477737   65758
9      Georgia    10617423   59425

In [7]:
df.head()

        State  Population    Area
0     Alabama     4903185   52420
1      Alaska      731545  665384
2     Arizona     7278717  113990
3    Arkansas     3017804   53179
4  California    39538223  163695

In [8]:
df.tail()

         State  Population    Area
5     Colorado     5758736  104094
6  Connecticut     3565287    5543
7     Delaware      973764    2489
8      Florida    21477737   65758
9      Georgia    10617423   59425

In [9]:
pd.DataFrame(data,columns=["State","Population","Area"])

         State  Population    Area
0      Alabama     4903185   52420
1       Alaska      731545  665384
2      Arizona     7278717  113990
3     Arkansas     3017804   53179
4   California    39538223  163695
5     Colorado     5758736  104094
6  Connecticut     3565287    5543
7     Delaware      973764    2489
8      Florida    21477737   65758
9      Georgia    10617423   59425

In [2]:
s = [1,2,3,3]
a = [1,2,3,3]
for i,j in zip(s,a):
    print(i,j)

1 1
2 2
3 3
3 3

In [10]:
def intersect( nums1, nums2):
        a = []
        for i in nums1:
            for j in nums2:
                if i==j :
                   a.append(i)
                   nums1.remove(i)
                   nums2.remove(j)
           
        return a
nums1 = [1,2,2,1]
nums2 = [2,2]
print(intersect(nums1, nums2))

[2]

In [5]:
nums1 = [1,2,2,1]
nums2 = [2,2]
print(intersect(nums1, nums2))

TypeError: intersect() missing 1 required positional argument: 'nums2'

In [2]:
import pandas as pd
data = {
'Country': ['Belgium', 'India', 'Brazil'],
'Capital': ['Brussels', 'New Delhi', 'Brasília'],
'Population': [11190846, 1303171035, 207847528]
}
df = pd.DataFrame(data)
print(df)

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasília   207847528