In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [71]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [72]:
df=pd.read_csv('housing.csv')

In [73]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [74]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

In [75]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [76]:
print(df.columns.to_list())

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']

In [77]:
target='median_house_value'

In [78]:
x=df.drop(columns=target)

In [79]:
y=df[target]

In [80]:
print("Before converstion")
x.head()
x=pd.get_dummies(x,drop_first=True)
x.head()

Before converstion

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,False,False,True,False

In [81]:
x.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,False,False,True,False

In [82]:
print(df.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [83]:
from sklearn.impute import SimpleImputer

In [84]:
imputer=SimpleImputer(strategy='median')

In [85]:
x_imputed_array=imputer.fit_transform(x)

In [86]:
x.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,False,False,True,False

In [87]:
print(x.isnull().sum())

longitude                       0
latitude                        0
housing_median_age              0
total_rooms                     0
total_bedrooms                207
population                      0
households                      0
median_income                   0
ocean_proximity_INLAND          0
ocean_proximity_ISLAND          0
ocean_proximity_NEAR BAY        0
ocean_proximity_NEAR OCEAN      0
dtype: int64

In [88]:
x=pd.DataFrame(x_imputed_array,columns=x.columns,index=x.index)

In [89]:
X_train, X_test, y_train, y_test = train_test_split(   x,
    y,
    test_size=0.2,
    random_state=42
)

In [90]:
linear= LinearRegression()

In [91]:
linear.fit(X_train,y_train)
y_pred_linear=linear.predict(X_test)
print("Actual values")
print(y_test.values)
print("predicted")
print(y_pred_linear)

Actual values
[ 47700.  45800. 500001. ... 500001.  72300. 151500.]
predicted
[ 54055.44889897 124225.33893718 255489.37949166 ... 439180.98341181
 120797.5524062  183386.04993584]

In [92]:
mae_linear=mean_absolute_error(y_test,y_pred_linear)
mse_linear=mean_squared_error(y_test,y_pred_linear)
rmse_linear=np.sqrt(mse_linear)
r2_linear=r2_score(y_test,y_pred_linear)

In [93]:
print("MAE:",round(mae_linear,2))
print("MSE",round(mse_linear,2))
print("RMSE:",round(rmse_linear,2))
print("R@ SCore:",round(r2_linear),2)

MAE: 50670.74
MSE 4908476721.16
RMSE: 70060.52
R@ SCore: 1 2

In [94]:
poly=PolynomialFeatures(degree=2,include_bias=False)

In [95]:
x_train_poly=poly.fit_transform(X_train)
x_test_poly=poly.transform(X_test)
poly_model=LinearRegression()
poly_model.fit(x_train_poly,y_train)
y_pred_poly=poly_model.predict(x_test_poly)
print("Actual values")
print(y_test.values)
print("predicted")
print(y_pred_poly)

Actual values
[ 47700.  45800. 500001. ... 500001.  72300. 151500.]
predicted
[ 77639.06751093 117809.25867293 318345.03524534 ... 448552.01764871
 119339.55401406 183053.63266204]

In [96]:
mae_poly=mean_absolute_error(y_test,y_pred_poly)
mse_poly=mean_squared_error(y_test,y_pred_poly)
rmse_poly=np.sqrt(mse_poly)
r2_poly=r2_score(y_test,y_pred_poly)

In [97]:
print("MAE:",round(mae_poly,2))
print("MSE",round(mse_poly,2))
print("RMSE:",round(rmse_poly,2))
print("R@ SCore:",round(r2_poly,2))

MAE: 49167.89
MSE 4730739020.72
RMSE: 68780.37
R@ SCore: 0.64